package com.saadqazi.currencyconverter.helpers

object Util {

    val currencyList = listOf(
        Triple("USD", "United States Dollar", "\uD83C\uDDFA\uD83C\uDDF8"),
        Triple("AED", "United Arab Emirates Dirham", "\uD83C\uDDE6\uD83C\uDDEA"),
        Triple("AFN", "Afghan Afghani", "\uD83C\uDDE6\uD83C\uDDEB"),
        Triple("ALL", "Albanian Lek", "\uD83C\uDDE6\uD83C\uDDF1"),
        Triple("AMD", "Armenian Dram", "\uD83C\uDDE6\uD83C\uDDF2"),
        Triple("ANG", "Netherlands Antillean Guilder", "\uD83C\uDDE6\uD83C\uDDF6"),
        Triple("AOA", "Angolan Kwanza", "\uD83C\uDDE6\uD83C\uDDF4"),
        Triple("ARS", "Argentine Peso", "\uD83C\uDDE6\uD83C\uDDF7"),
        Triple("AUD", "Australian Dollar", "\uD83C\uDDE6\uD83C\uDDFA"),
        Triple("AWG", "Aruban Florin", "\uD83C\uDDE6\uD83C\uDDFC"),
        Triple("AZN", "Azerbaijani Manat", "\uD83C\uDDE6\uD83C\uDDFF"),
        Triple("BAM", "Bosnia-Herzegovina Convertible Mark", "\uD83C\uDDE7\uD83C\uDDE6"),
        Triple("BBD", "Barbadian Dollar", "\uD83C\uDDE7\uD83C\uDDE7"),
        Triple("BDT", "Bangladeshi Taka", "\uD83C\uDDE7\uD83C\uDDE9"),
        Triple("BGN", "Bulgarian Lev", "\uD83C\uDDE7\uD83C\uDDEC"),
        Triple("BHD", "Bahraini Dinar", "\uD83C\uDDE7\uD83C\uDDED"),
        Triple("BIF", "Burundian Franc", "\uD83C\uDDE7\uD83C\uDDEE"),
        Triple("BMD", "Bermudian Dollar", "\uD83C\uDDE7\uD83C\uDDF2"),
        Triple("BND", "Brunei Dollar", "\uD83C\uDDE7\uD83C\uDDF3"),
        Triple("BOB", "Bolivian Boliviano", "\uD83C\uDDE7\uD83C\uDDF4"),
        Triple("BRL", "Brazilian Real", "\uD83C\uDDE7\uD83C\uDDF7"),
        Triple("BSD", "Bahamian Dollar", "\uD83C\uDDE7\uD83C\uDDF8"),
        Triple("BTN", "Bhutanese Ngultrum", "\uD83C\uDDE7\uD83C\uDDF9"),
        Triple("BWP", "Botswana Pula", "\uD83C\uDDE7\uD83C\uDDFC"),
        Triple("BYN", "Belarusian Ruble", "\uD83C\uDDE7\uD83C\uDDFE"),
        Triple("BZD", "Belize Dollar", "\uD83C\uDDE7\uD83C\uDDFF"),
        Triple("CAD", "Canadian Dollar", "\uD83C\uDDE8\uD83C\uDDE6"),
        Triple("CDF", "Congolese Franc", "\uD83C\uDDE8\uD83C\uDDE9"),
        Triple("CHF", "Swiss Franc", "\uD83C\uDDE8\uD83C\uDDED"),
        Triple("CLP", "Chilean Peso", "\uD83C\uDDE8\uD83C\uDDF1"),
        Triple("CNY", "Chinese Yuan", "\uD83C\uDDE8\uD83C\uDDF3"),
        Triple("COP", "Colombian Peso", "\uD83C\uDDE8\uD83C\uDDF4"),
        Triple("CRC", "Costa Rican Colón", "\uD83C\uDDE8\uD83C\uDDF7"),
        Triple("CUP", "Cuban Peso", "\uD83C\uDDE8\uD83C\uDDFA"),
        Triple("CVE", "Cape Verdean Escudo", "\uD83C\uDDE8\uD83C\uDDFB"),
        Triple("CZK", "Czech Koruna", "\uD83C\uDDE8\uD83C\uDDFF"),
        Triple("DJF", "Djiboutian Franc", "\uD83C\uDDE9\uD83C\uDDEF"),
        Triple("DKK", "Danish Krone", "\uD83C\uDDE9\uD83C\uDDF0"),
        Triple("DOP", "Dominican Peso", "\uD83C\uDDE9\uD83C\uDDF4"),
        Triple("DZD", "Algerian Dinar", "\uD83C\uDDE9\uD83C\uDDFF"),
        Triple("EGP", "Egyptian Pound", "\uD83C\uDDEA\uD83C\uDDEC"),
        Triple("ERN", "Eritrean Nakfa", "\uD83C\uDDEA\uD83C\uDDF7"),
        Triple("ETB", "Ethiopian Birr", "\uD83C\uDDEA\uD83C\uDDF9"),
        Triple("EUR", "Euro", "\uD83C\uDDEA\uD83C\uDDFA"),
        Triple("FJD", "Fijian Dollar", "\uD83C\uDDEB\uD83C\uDDEF"),
        Triple("FKP", "Falkland Islands Pound", "\uD83C\uDDEB\uD83C\uDDF0"),
        Triple("FOK", "Faroese Króna", "\uD83C\uDDEB\uD83C\uDDF4"),
        Triple("GBP", "British Pound Sterling", "\uD83C\uDDEC\uD83C\uDDE7"),
        Triple("GEL", "Georgian Lari", "\uD83C\uDDEC\uD83C\uDDEA"),
        Triple("GGP", "Guernsey Pound", "\uD83C\uDDEC\uD83C\uDDEC"),
        Triple("GHS", "Ghanaian Cedi", "\uD83C\uDDEC\uD83C\uDDED"),
        Triple("GIP", "Gibraltar Pound", "\uD83C\uDDEC\uD83C\uDDEE"),
        Triple("GMD", "Gambian Dalasi", "\uD83C\uDDEC\uD83C\uDDF2"),
        Triple("GNF", "Guinean Franc", "\uD83C\uDDEC\uD83C\uDDF3"),
        Triple("GTQ", "Guatemalan Quetzal", "\uD83C\uDDEC\uD83C\uDDF9"),
        Triple("GYD", "Guyanaese Dollar", "\uD83C\uDDEC\uD83C\uDDFE"),
        Triple("HKD", "Hong Kong Dollar", "\uD83C\uDDEC\uD83C\uDDE9"),
        Triple("HNL", "Honduran Lempira", "\uD83C\uDDED\uD83C\uDDF3"),
        Triple("HRK", "Croatian Kuna", "\uD83C\uDDED\uD83C\uDDF7"),
        Triple("HTG", "Haitian Gourde", "\uD83C\uDDED\uD83C\uDDF9"),
        Triple("HUF", "Hungarian Forint", "\uD83C\uDDED\uD83C\uDDFA"),
        Triple("IDR", "Indonesian Rupiah", "\uD83C\uDDEE\uD83C\uDDE9"),
        Triple("ILS", "Israeli New Shekel", "\uD83C\uDDEE\uD83C\uDDF1"),
        Triple("IMP", "Isle of Man Pound", "\uD83C\uDDEE\uD83C\uDDF2"),
        Triple("INR", "Indian Rupee", "\uD83C\uDDEE\uD83C\uDDF3"),
        Triple("IQD", "Iraqi Dinar", "\uD83C\uDDEE\uD83C\uDDF6"),
        Triple("IRR", "Iranian Rial", "\uD83C\uDDEE\uD83C\uDDF7"),
        Triple("ISK", "Icelandic Króna", "\uD83C\uDDEE\uD83C\uDDF8"),
        Triple("JEP", "Jersey Pound", "\uD83C\uDDEF\uD83C\uDDEA"),
        Triple("JMD", "Jamaican Dollar", "\uD83C\uDDEF\uD83C\uDDF2"),
        Triple("JOD", "Jordanian Dinar", "\uD83C\uDDEF\uD83C\uDDF4"),
        Triple("JPY", "Japanese Yen", "\uD83C\uDDEF\uD83C\uDDF5"),
        Triple("KES", "Kenyan Shilling", "\uD83C\uDDF0\uD83C\uDDEA"),
        Triple("KGS", "Kyrgystani Som", "\uD83C\uDDF0\uD83C\uDDEC"),
        Triple("KHR", "Cambodian Riel", "\uD83C\uDDF0\uD83C\uDDED"),
        Triple("KID", "Kiribati Dollar", "\uD83C\uDDF0\uD83C\uDDEE"),
        Triple("KMF", "Comorian Franc", "\uD83C\uDDF0\uD83C\uDDEA"),
        Triple("KRW", "South Korean Won", "\uD83C\uDDF0\uD83C\uDDF7"),
        Triple("KWD", "Kuwaiti Dinar", "\uD83C\uDDF0\uD83C\uDDFC"),
        Triple("KYD", "Cayman Islands Dollar", "\uD83C\uDDF0\uD83C\uDDFE"),
        Triple("KZT", "Kazakhstani Tenge", "\uD83C\uDDF0\uD83C\uDDFF"),
        Triple("LAK", "Laotian Kip", "\uD83C\uDDF1\uD83C\uDDE6"),
        Triple("LBP", "Lebanese Pound", "\uD83C\uDDF1\uD83C\uDDE7"),
        Triple("LKR", "Sri Lankan Rupee", "\uD83C\uDDF1\uD83C\uDDF0"),
        Triple("LRD", "Liberian Dollar", "\uD83C\uDDF1\uD83C\uDDF7"),
        Triple("LSL", "Lesotho Loti", "\uD83C\uDDF1\uD83C\uDDF8"),
        Triple("LYD", "Libyan Dinar", "\uD83C\uDDF1\uD83C\uDDFE"),
        Triple("MAD", "Moroccan Dirham", "\uD83C\uDDF2\uD83C\uDDE6"),
        Triple("MDL", "Moldovan Leu", "\uD83C\uDDF2\uD83C\uDDE9"),
        Triple("MGA", "Malagasy Ariary", "\uD83C\uDDF2\uD83C\uDDEC"),
        Triple("MKD", "Macedonian Denar", "\uD83C\uDDF2\uD83C\uDDF0"),
        Triple("MMK", "Myanmar Kyat", "\uD83C\uDDF2\uD83C\uDDF2"),
        Triple("MNT", "Mongolian Tugrik", "\uD83C\uDDF2\uD83C\uDDF3"),
        Triple("MOP", "Macanese Pataca", "\uD83C\uDDF2\uD83C\uDDF4"),
        Triple("MRU", "Mauritanian Ouguiya", "\uD83C\uDDF2\uD83C\uDDF7"),
        Triple("MUR", "Mauritian Rupee", "\uD83C\uDDF2\uD83C\uDDF7"),
        Triple("MVR", "Maldivian Rufiyaa", "\uD83C\uDDF2\uD83C\uDDF8"),
        Triple("MWK", "Malawian Kwacha", "\uD83C\uDDF2\uD83C\uDDFC"),
        Triple("MXN", "Mexican Peso", "\uD83C\uDDF2\uD83C\uDDFD"),
        Triple("MYR", "Malaysian Ringgit", "\uD83C\uDDF2\uD83C\uDDFE"),
        Triple("MZN", "Mozambican Metical", "\uD83C\uDDF2\uD83C\uDDFF"),
        Triple("NAD", "Namibian Dollar", "\uD83C\uDDF3\uD83C\uDDE6"),
        Triple("NGN", "Nigerian Naira", "\uD83C\uDDF3\uD83C\uDDEC"),
        Triple("NIO", "Nicaraguan Córdoba", "\uD83C\uDDF3\uD83C\uDDEE"),
        Triple("NOK", "Norwegian Krone", "\uD83C\uDDF3\uD83C\uDDF4"),
        Triple("NPR", "Nepalese Rupee", "\uD83C\uDDF3\uD83C\uDDF5"),
        Triple("NZD", "New Zealand Dollar", "\uD83C\uDDF3\uD83C\uDDFF"),
        Triple("OMR", "Omani Rial", "\uD83C\uDDF4\uD83C\uDDF2"),
        Triple("PAB", "Panamanian Balboa", "\uD83C\uDDF5\uD83C\uDDE6"),
        Triple("PEN", "Peruvian Nuevo Sol", "\uD83C\uDDF5\uD83C\uDDEA"),
        Triple("PGK", "Papua New Guinean Kina", "\uD83C\uDDF5\uD83C\uDDEC"),
        Triple("PHP", "Philippine Peso", "\uD83C\uDDF5\uD83C\uDDED"),
        Triple("PKR", "Pakistani Rupee", "\uD83C\uDDF5\uD83C\uDDF0"),
        Triple("PLN", "Polish Zloty", "\uD83C\uDDF5\uD83C\uDDF1"),
        Triple("PYG", "Paraguayan Guarani", "\uD83C\uDDF5\uD83C\uDDFE"),
        Triple("QAR", "Qatari Rial", "\uD83C\uDDF6\uD83C\uDDE6"),
        Triple("RON", "Romanian Leu", "\uD83C\uDDF7\uD83C\uDDF4"),
        Triple("RSD", "Serbian Dinar", "\uD83C\uDDF7\uD83C\uDDF8"),
        Triple("RUB", "Russian Ruble", "\uD83C\uDDF7\uD83C\uDDFA"),
        Triple("RWF", "Rwandan Franc", "\uD83C\uDDF7\uD83C\uDDFC"),
        Triple("SAR", "Saudi Riyal", "\uD83C\uDDF8\uD83C\uDDE6"),
        Triple("SBD", "Solomon Islands Dollar", "\uD83C\uDDF8\uD83C\uDDE7"),
        Triple("SCR", "Seychellois Rupee", "\uD83C\uDDF8\uD83C\uDDE8"),
        Triple("SDG", "Sudanese Pound", "\uD83C\uDDF8\uD83C\uDDE9"),
        Triple("SEK", "Swedish Krona", "\uD83C\uDDF8\uD83C\uDDEA"),
        Triple("SGD", "Singapore Dollar", "\uD83C\uDDF8\uD83C\uDDEC"),
        Triple("SHP", "Saint Helena Pound", "\uD83C\uDDF8\uD83C\uDDED"),
        Triple("SLL", "Sierra Leonean Leone", "\uD83C\uDDF8\uD83C\uDDF1"),
        Triple("SOS", "Somali Shilling", "\uD83C\uDDF8\uD83C\uDDF4"),
        Triple("SRD", "Surinamese Dollar", "\uD83C\uDDF8\uD83C\uDDF7"),
        Triple("SSP", "South Sudanese Pound", "\uD83C\uDDF8\uD83C\uDDF8"),
        Triple("STN", "São Tomé and Príncipe Dobra", "\uD83C\uDDF8\uD83C\uDDF9"),
        Triple("SYP", "Syrian Pound", "\uD83C\uDDF8\uD83C\uDDFE"),
        Triple("SZL", "Swazi Lilangeni", "\uD83C\uDDF8\uD83C\uDDFF"),
        Triple("THB", "Thai Baht", "\uD83C\uDDF9\uD83C\uDDED"),
        Triple("TJS", "Tajikistani Somoni", "\uD83C\uDDF9\uD83C\uDDEF"),
        Triple("TMT", "Turkmenistani Manat", "\uD83C\uDDF9\uD83C\uDDF2"),
        Triple("TND", "Tunisian Dinar", "\uD83C\uDDF9\uD83C\uDDF3"),
        Triple("TOP", "Tongan Pa'anga", "\uD83C\uDDF9\uD83C\uDDF4"),
        Triple("TRY", "Turkish Lira", "\uD83C\uDDF9\uD83C\uDDF7"),
        Triple("TTD", "Trinidad and Tobago Dollar", "\uD83C\uDDF9\uD83C\uDDF9"),
        Triple("TVD", "Tuvaluan Dollar", "\uD83C\uDDF9\uD83C\uDDFB"),
        Triple("TWD", "New Taiwan Dollar", "\uD83C\uDDF9\uD83C\uDDFC"),
        Triple("TZS", "Tanzanian Shilling", "\uD83C\uDDF9\uD83C\uDDFF"),
        Triple("UAH", "Ukrainian Hryvnia", "\uD83C\uDDFA\uD83C\uDDE6"),
        Triple("UGX", "Ugandan Shilling", "\uD83C\uDDFA\uD83C\uDDEC"),
        Triple("UYU", "Uruguayan Peso", "\uD83C\uDDFA\uD83C\uDDFE"),
        Triple("UZS", "Uzbekistan Som", "\uD83C\uDDFA\uD83C\uDDFF"),
        Triple("VES", "Venezuelan Bolívar", "\uD83C\uDDFB\uD83C\uDDEA"),
        Triple("VND", "Vietnamese Dong", "\uD83C\uDDFB\uD83C\uDDF3"),
        Triple("VUV", "Vanuatu Vatu", "\uD83C\uDDFB\uD83C\uDDFA"),
        Triple("WST", "Samoan Tala", "\uD83C\uDDFC\uD83C\uDDF8"),
        Triple("XAF", "CFA Franc BEAC", "\uD83C\uDDE8\uD83C\uDDEB"),
        Triple("XCD", "East Caribbean Dollar", "\uD83C\uDDE8\uD83C\uDDEC"),
        Triple("XDR", "Special Drawing Rights", "\uD83C\uDDE8\uD83C\uDDF7"),
        Triple("XOF", "CFA Franc BCEAO", "\uD83C\uDDE8\uD83C\uDDF3"),
        Triple("XPF", "CFP Franc", "\uD83C\uDDE8\uD83C\uDDF5"),
        Triple("YER", "Yemeni Rial", "\uD83C\uDDF2\uD83C\uDDEA"),
        Triple("ZAR", "South African Rand", "\uD83C\uDDFF\uD83C\uDDE6"),
        Triple("ZMW", "Zambian Kwacha", "\uD83C\uDDFF\uD83C\uDDF2"),
        Triple("ZWL", "Zimbabwean Dollar", "\uD83C\uDDFF\uD83C\uDDFC")
    )

}